#!/bin/bash

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

riverctl spawn "wlr-randr --output HDMI-A-1 --mode 1920x1080@75.002998"
riverctl spawn "foot --server"
riverctl spawn "dunst"
riverctl spawn "swaybg -i $HOME/wallpaper/fish_2.jpg"
riverctl spawn yambar
riverctl allow-tearing enabled
riverctl keyboard-layout -options "grp:ctrl_space_toggle" "us,ru"
riverctl map -layout 0 normal Super Right spawn "wlr-randr --output HDMI-A-1 --mode 1920x1080@75.002998 --transform 90"
riverctl map -layout 0 normal Super Left spawn "wlr-randr --output HDMI-A-1 --mode 1920x1080@75.002998 --transform normal"
riverctl map -layout 0 normal Super Return spawn "footclient"
riverctl map -layout 0 normal Super+Control Return spawn "fuzzel"
riverctl map -layout 0 normal Super B spawn firefox 
riverctl map -layout 0 normal Super E spawn "thunar"
# Super+Q to close the focused view
riverctl map -layout 0 normal Super Q close
riverctl map -layout 0 normal Super S spawn "~/.config/river/screenshot_area.sh"
riverctl map -layout 0 normal Super+Shift S spawn "~/.config/river/screenshot.sh"
riverctl map -layout 0 normal Super R spawn "~/.config/river/screencap_area.sh"
riverctl map -layout 0 normal Super+Control R spawn "~/.config/river/screencap_area_audio.sh"
riverctl map -layout 0 normal Super+Shift+Control R spawn "~/.config/river/screencap_audio.sh"
riverctl map -layout 0 normal Super+Shift R spawn "~/.config/river/screencap.sh"
# Super+Shift+E to exit river
riverctl map -layout 0 normal Super+Shift E exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt H resize horizontal -100
riverctl map normal Super+Alt J resize vertical 100
riverctl map normal Super+Alt K resize vertical -100
riverctl map normal Super+Alt L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view
# Super + tRight Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view
# Supert + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map -layout 0 normal Super T toggle-float

# Super+F to toggle fullscreen
riverctl map -layout 0 normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x0000ff
riverctl border-color-unfocused 0x000000
riverctl border-width 1
# Set keyboard repeat rate
riverctl set-repeat 50 300

dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
systemctl --user restart xdg-desktop-portal xdg-desktop-portal-wlr
# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl focus-follows-cursor always
riverctl default-layout bsp-layout 
river-bsp-layout --inner-gap 0 --outer-gap 0 --split-perc 0.5 

